### ISSUE TITLE
Update font version

### ISSUE THREAD

**Issue by ZAYEC77** [mrkelly/lato#7]
Can you update font version to 2.010?

**Comment by ynnoj** [comment]
This is done in [#9](https://github.com/mrkelly/lato/pull/9).

**Comment by ZAYEC77** [comment]
@ynnoj thanks

**Comment by ynnoj** [comment]
@ZAYEC77 You can include my repo in your `bower.json` until the PR is merged.

```json
"lato": "ynnoj/lato#master"

**Comment by ZAYEC77** [comment]
@ynnoj thanks, I did it
